-- Membuat tabel Loans untuk mikroservis
CREATE TABLE loans
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    loan_date   DATE         NOT NULL,
    due_date    DATE         NOT NULL,
    return_date DATE,
    status      VARCHAR(255) NOT NULL
);

-- Membuat tabel Fines untuk mikroservis dengan referensi ke Loans
CREATE TABLE fines
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id     BIGINT         NOT NULL,
    user_id     BIGINT         NOT NULL,
    amount      NUMERIC(10, 2) NOT NULL,
    reason      TEXT,
    status      VARCHAR(255)   NOT NULL,
    issued_date DATE           NOT NULL,
    paid_date   DATE,
    FOREIGN KEY (loan_id) REFERENCES loans (id)
);