CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    phone_number    VARCHAR(20)  NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    username        VARCHAR(255) NOT NULL UNIQUE,
    address         TEXT,
    identity_number VARCHAR(50)  NOT NULL UNIQUE,
    type_identity   VARCHAR(10)  NOT NULL CHECK (type_identity IN ('KTP', 'SIM', 'PASPOR'))
);