-- Membuat tabel Authors
CREATE TABLE authors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bio  TEXT
);

-- Membuat tabel Publishers
CREATE TABLE publishers
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    address TEXT
);

-- Membuat tabel Books dengan foreign keys yang terhubung ke tabel Authors dan Publishers
CREATE TABLE books
(
    id               SERIAL PRIMARY KEY,
    title            VARCHAR(255)       NOT NULL,
    isbn             VARCHAR(13) UNIQUE NOT NULL,
    publication_year INT,
    status           VARCHAR(50),
    qr_code          VARCHAR(255),
    author_id        INT,
    publisher_id     INT,
    FOREIGN KEY (author_id) REFERENCES authors (id),
    FOREIGN KEY (publisher_id) REFERENCES publishers (id)
);