services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=users_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=secret'
    ports:
      - '5002:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data/
volumes:
  pg-data:
    driver: local
